### ISSUE TITLE
/login (POST)

### ISSUE THREAD

**Issue by mankiww** [onCondition/onCondition-server#28]
* findOrCreate 를 User model 에 설치하기.
   - (find) 만일 입력한  email이 우리 user에 존재한다면, 이미 회원가입을 한 것이기 때문에 update로 넘어감. 
    - (update) find 하고, 무조건 사진url(picture)과 username(name)은 비교해서 우리가 가진 값과 다르면 update.
   - (create) 입력한  email이 우리  user에 존재하지 않는다면, 신규 회원가입으로 처리하여 새로운 회원정보를 만들어줌. 

- 이후 google fit에 요청 보내서 가장 최근 로그인 시점 이후의 걸음, 운동, 수면 데이터를 가져오고, 몽고디비에 추가.

req
- header `Authorization: Bearer [TOKEN]`

res
- 200 `{ result: 'ok' }`
- 401 `{ error: 'unauthorized' }`
- 500 `{ error: 'internal server error' }`

**Comment by Ken123777** [comment]
logout은 없나요?
