### ISSUE TITLE
/friends (GET)

### ISSUE THREAD

**Issue by hayjo** [onCondition/onCondition-server#5]
- req
  - header `Authorization Bearer [TOKEN]`
  - body `{ page: Number | default: 0 }`
- res
  - 200
 ```
{
  friends: [{
    id: mongooseObjectId,
    profile_url: String,
    name: String,
    recently_rated_date: Date,
    stroke: Number,
    scores: [{  meal: Number,  sleep: Number,  }]
  }],
  pending_friends: [{
    id: mongooseObjectId,
    profile_url: String,
    name: String
  }],
  currentPage: Number
}
```
  - 400 `{ error: 'invalid page number' }`
  - 401 `{ error: 'unauthorized' }`
  - 500 `{ error: 'internal server error' }`

- Description
  - friends: 친구목록 무한스크롤로 구현될 것이므로 stroke 내림차순으로 pagination 된 결과 전달하고, 현재 페이지 번호 함께 전달
  - friends/scores: Array({ maxLength: 30 }), 카테고리별 만족도(score)가 30일 어치 누적되어있는 배열
  - 한번에 보내줄 카드수 논의 필요
  - 친구 탭에 보여지는 나의 친구 목록 데이터

**Comment by mankiww** [comment]
pending_friends -> 친구 요청을 보낸 친구, 친구 요청을 받은 친구로 나눠야 할 것 같습니다. 
변수명 정해지면 업데이트 부탁드립니다.
